url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Kimini Medical
email: Contact@kimini-med.com
description: "Painless and self-executable blood collection device for home, clinic, and remote diagnostics."


# Team names, titles and social links
people:
- name: Nguyen Minh Duc (Ph.D.)
  pic: 1
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nguyenminhduc/

- name: Frank Nguyen (Ph.D.)
  pic: 2
  position: COO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/lam-nguyen-ba6832264/

- name: Mike Cuong (Ph.D.)
  pic: 3
  position: CSO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/van-cuong-mai-9b6135131/

- name: Duong Phan Khanh (Ph.D.)
  pic: 4
  position: CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/phan-khanh-duong-a258a668/

- name: Than Duc Huy
  pic: 5
  position: Tech Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/than-duc-huy/
    

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: NTU Innovation Centre
  - line: 71 Nanyang Drive, #03-01, Singapore 638075.

# Build settings
markdown: kramdown
permalink: pretty