url: ""
baseurl: ""

# Site settings
title: Kimini Medical
email: contact@kimini-med.com
description: >-
  Kimini Medical is developing a painless blood self-collection system designed
  to improve access to blood testing in difficult-to-draw and decentralized settings.
url: "https://kimini-med.com"
baseurl: ""


# Team names, titles and social links
people:
- name: Nguyen Minh Duc (Ph.D.)
  pic: 1
  position: CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nguyenminhduc/

- name: Frank Nguyen (Ph.D.)
  pic: 2
  position: COO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/lam-nguyen-ba6832264/

- name: Mike Cuong (Ph.D.)
  pic: 3
  position: CSO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/van-cuong-mai-9b6135131/

- name: Duong Phan Khanh (Ph.D.)
  pic: 4
  position: CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/phan-khanh-duong-a258a668/

- name: Than Duc Huy
  pic: 5
  position: Tech Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/than-duc-huy/
    

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/kimini-medical

# Postal address (add as many lines as necessary)
address:
  - line: NTU Innovation Centre
  - line: 71 Nanyang Drive, #03-01, Singapore 638075.

# Build settings
markdown: kramdown
permalink: pretty